# Generated by Django 5.0.7 on 2025-10-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=20)),
                ('assembly_no', models.IntegerField()),
                ('constituency_no', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('delimid', models.IntegerField()),
                ('position', models.IntegerField()),
                ('candidate', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('party', models.CharField(max_length=50)),
                ('votes', models.FloatField()),
                ('candidate_type', models.CharField(blank=True, max_length=100, null=True)),
                ('valid_votes', models.IntegerField()),
                ('electors', models.FloatField()),
                ('constituency_name', models.CharField(max_length=150)),
                ('constituency_type', models.CharField(max_length=50)),
                ('n_cand', models.IntegerField()),
                ('turnout_percentage', models.FloatField()),
                ('vote_share_percentage', models.FloatField()),
                ('deposit_lost', models.CharField(max_length=10)),
                ('margin', models.FloatField()),
                ('margin_percentage', models.FloatField()),
                ('enop', models.FloatField()),
                ('pid', models.CharField(max_length=50)),
                ('party_type_tcpd', models.CharField(max_length=50)),
                ('party_id', models.FloatField()),
                ('last_poll', models.BooleanField()),
                ('contested', models.FloatField()),
                ('no_terms', models.FloatField(blank=True, null=True)),
                ('turncoat', models.CharField(max_length=10)),
                ('incumbent', models.CharField(max_length=10)),
                ('recontest', models.CharField(max_length=10)),
                ('myneta_education', models.CharField(blank=True, max_length=100, null=True)),
                ('tcpd_prof_main', models.CharField(blank=True, max_length=100, null=True)),
                ('tcpd_prof_main_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('election_type', models.CharField(max_length=100)),
            ],
        ),
    ]
