# Generated by Django 5.0.7 on 2025-10-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionresult',
            name='month',
            field=models.FloatField(),
        ),
    ]
