# Generated by Django 5.0.7 on 2025-10-14 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_electionresult_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='dashboard.state')),
            ],
            options={
                'unique_together': {('name', 'state')},
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(default='Unknown', max_length=10)),
                ('votes', models.BigIntegerField(default=0)),
                ('vote_share_percentage', models.FloatField(default=0.0)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('margin', models.BigIntegerField(blank=True, null=True)),
                ('turnout_percentage', models.FloatField(blank=True, null=True)),
                ('result_status', models.CharField(default='Unknown', max_length=20)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.constituency')),
                ('election_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.electionyear')),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.party')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.state')),
            ],
            options={
                'indexes': [models.Index(fields=['election_year', 'state', 'party'], name='dashboard_c_electio_8f1312_idx'), models.Index(fields=['constituency', 'state'], name='dashboard_c_constit_9935d8_idx')],
            },
        ),
    ]
