# Generated by Django 5.0.7 on 2025-10-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_electionyear_party_state_constituency_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='votes',
            field=models.FloatField(default=0.0),
        ),
    ]
