# Generated by Django 5.0.7 on 2025-10-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_education_delete_electionresult_candidate_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('state_name', models.CharField(max_length=150)),
                ('constituency_name', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('education', models.CharField(default='Unknown', max_length=100)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('result_status', models.CharField(default='Unknown', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='education',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
